version: 2.1
jobs:
  build:
    macos:
      xcode: "12.4.0"
    steps:
      - checkout
      - run:
          name: Install carthage
          command: |
            brew update
            brew outdated carthage || brew upgrade carthage
      - run:
          name: Build Frameworks
          command: sh build.sh
      - store_artifacts:
          path: ./output
          destination: Frameworks
