# Uncomment the next line to define a global platform for your project
# platform :ios, '15.0'

target 'AttributesInspector' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AttributesInspector

end

target 'HyperionCore' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HyperionCore

end

target 'Measurements' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Measurements

end

target 'SlowAnimations' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SlowAnimations

end
